-- MIN/MAX Engine v5 HYBRID — tabele de persistenta a rularilor
-- Ruleaza in baza S1 (DUBHE ROMANIA SRL, company 1000).
-- Idempotent: DDL cu IF NOT EXISTS. Instalat din /JS/NewMinMax/setup.
-- Referinta: new_min_max/PLAN_IMPLEMENTARE.md sectiunea 4.

--=====================================================================
-- 1. CCCMINMAXRUN — antet rulare, versionat (rularile NU se suprascriu)
--=====================================================================

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CCCMINMAXRUN' AND xtype='U')
CREATE TABLE CCCMINMAXRUN (
    RUNID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    COMPANY SMALLINT NOT NULL,
    AZI DATE NULL,
    FAZA VARCHAR(20) NOT NULL DEFAULT 'CLASSIFY',
    STATUS VARCHAR(10) NOT NULL DEFAULT 'RUNNING',
    MTRL INT NULL,
    NR_RANDURI INT NULL,
    DURATA_SEC INT NULL,
    PARAMSJSON NVARCHAR(MAX) NULL,
    ERRORMSG NVARCHAR(500) NULL,
    STARTEDAT DATETIME NOT NULL DEFAULT GETDATE(),
    FINISHEDAT DATETIME NULL,
    CREATEDBY INT NULL,
    COMPUTE_STATUS VARCHAR(10) NULL,
    COMPUTE_STARTEDAT DATETIME NULL,
    COMPUTE_FINISHEDAT DATETIME NULL,
    COMPUTE_DURATA_SEC INT NULL,
    COMPUTE_PARAMSJSON NVARCHAR(MAX) NULL,
    COMPUTE_ERRORMSG NVARCHAR(500) NULL
);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_CCCMINMAXRUN_COMPANY_STARTED')
CREATE INDEX IX_CCCMINMAXRUN_COMPANY_STARTED ON CCCMINMAXRUN(COMPANY, STARTEDAT DESC);

--=====================================================================
-- 2. CCCMINMAXDET — rezultat per SKU x filiala, atasat unui RUNID
--    Coloanele de clasificare sunt scrise de sp_MinMaxEngine_Classify.
--    Faza 3 (sp_MinMaxEngine_Compute) adauga propriile coloane de calcul.
--=====================================================================

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CCCMINMAXDET' AND xtype='U')
CREATE TABLE CCCMINMAXDET (
    RUNID INT NOT NULL,
    COMPANY SMALLINT NOT NULL,
    AZI DATE NOT NULL,
    BRANCH SMALLINT NOT NULL,
    MARIME VARCHAR(6) NULL,
    ESTE_HQ BIT NOT NULL,
    ESTE_PODEA BIT NOT NULL,
    MTRL INT NOT NULL,
    MTRSUP INT NULL,
    CODE VARCHAR(50) NULL,
    MTRL_NAME VARCHAR(128) NULL,
    MTRGROUP INT NULL,
    MTRGROUP_CODE VARCHAR(10) NULL,
    MTRGROUP_NAME VARCHAR(50) NULL,
    VZ_4S DECIMAL(28, 8) NULL,
    VZ_13S DECIMAL(28, 8) NULL,
    VZ_26S DECIMAL(28, 8) NULL,
    VZ_52S DECIMAL(28, 8) NULL,
    VAL_52S DECIMAL(28, 8) NULL,
    SAPT_VZ INT NULL,
    SAPT_8S INT NULL,
    SAPT_FARA INT NULL,
    ULT_VANZ DATETIME NULL,
    MIN_DOC DECIMAL(28, 8) NULL,
    SIGMA_WK DECIMAL(28, 8) NULL,
    SIGMA_WK_SUMSQ DECIMAL(38, 8) NULL,
    LUNI_VZ INT NULL,
    MAX_LUNA_QTY DECIMAL(28, 8) NULL,
    MEAN_MTH DECIMAL(28, 8) NULL,
    SIGMA_MTH DECIMAL(28, 8) NULL,
    SIGMA_MTH_SUMSQ DECIMAL(38, 8) NULL,
    CV DECIMAL(28, 8) NULL,
    IS_FORCED_Z BIT NULL,
    LIFECYCLE VARCHAR(10) NULL,
    ABC VARCHAR(1) NULL,
    XYZ VARCHAR(1) NULL,
    CLASA VARCHAR(3) NULL,
    COV_TGT DECIMAL(10, 4) NULL,
    SL DECIMAL(10, 4) NULL,
    SSF DECIMAL(10, 4) NULL,
    LT_ZILE INT NULL,
    FRECVENTA_ZILE INT NULL,
    [AVG] DECIMAL(28, 8) NULL,
    ad DECIMAL(28, 8) NULL,
    PREV_CUMULATIVE_PCT DECIMAL(28, 8) NULL,
    CUMULATIVE_PCT DECIMAL(28, 8) NULL,
    GRP_TOTAL_VAL DECIMAL(28, 8) NULL,
    GRP_ITEM_COUNT INT NULL,
    WARN_GRUPA_MICA BIT NULL,
    STOC_QTY DECIMAL(28, 8) NULL,
    ORD_FURN DECIMAL(28, 8) NULL,
    N_PACK DECIMAL(28, 8) NULL,
    ERP_MIN DECIMAL(28, 8) NULL,
    ERP_MAX DECIMAL(28, 8) NULL,
    ERP_MIN_AUTO DECIMAL(28, 8) NULL,
    ERP_MAX_AUTO DECIMAL(28, 8) NULL,
    LAST_RECEIPT DATETIME NULL,
    ARE_POZITIE_ERP BIT NULL,
    FLAG_LICHIDARE BIT NULL,
    FLAG_BLOCAT BIT NULL,
    FLAG_EXCLUS BIT NULL,
    SAFETY DECIMAL(28, 8) NULL,
    LT_STOCK DECIMAL(28, 8) NULL,
    SLTS DECIMAL(28, 8) NULL,
    BUF DECIMAL(28, 8) NULL,
    CYCLE DECIMAL(28, 8) NULL,
    MAX_RAW DECIMAL(28, 8) NULL,
    MAX_INF DECIMAL(28, 8) NULL,
    CAP6 DECIMAL(28, 8) NULL,
    VZ26_CAP DECIMAL(28, 8) NULL,
    SUM_BR_MAX DECIMAL(28, 8) NULL,
    ENG_MIN DECIMAL(28, 8) NULL,
    ENG_MAX DECIMAL(28, 8) NULL,
    BUY_RAW DECIMAL(28, 8) NULL,
    BUY_QTY DECIMAL(28, 8) NULL,
    HQ_CAP_APLICAT BIT NULL,
    PODEA_APLICATA BIT NULL,
    ACOP_CUR DECIMAL(28, 8) NULL,
    FLAG_RATIO DECIMAL(28, 8) NULL,
    FLAG_TXT VARCHAR(20) NULL,
    TREND_PCT DECIMAL(28, 8) NULL,
    STATUS_TREND VARCHAR(20) NULL,
    DISC_FLAG BIT NULL,
    WARN_VZ26_ZERO BIT NULL,
    WARN_STOC_NEG BIT NULL,
    WARN_STOC_MORT BIT NULL,
    CONSTRAINT PK_CCCMINMAXDET PRIMARY KEY CLUSTERED (RUNID, BRANCH, MTRL)
);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_CCCMINMAXDET_RUN_MTRL')
CREATE INDEX IX_CCCMINMAXDET_RUN_MTRL ON CCCMINMAXDET(RUNID, MTRL);

--=====================================================================
-- 3. CCCMINMAXWEEK — serie saptamanala rara per rulare
--=====================================================================

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CCCMINMAXWEEK' AND xtype='U')
CREATE TABLE CCCMINMAXWEEK (
    RUNID INT NOT NULL,
    COMPANY SMALLINT NOT NULL,
    BRANCH SMALLINT NOT NULL,
    MTRL INT NOT NULL,
    WEEK_INDEX SMALLINT NOT NULL,
    QTY DECIMAL(28, 8) NOT NULL,
    SALES_VALUE DECIMAL(28, 8) NOT NULL,
    LAST_POSITIVE_SALE DATETIME NULL,
    CONSTRAINT PK_CCCMINMAXWEEK PRIMARY KEY CLUSTERED (RUNID, BRANCH, MTRL, WEEK_INDEX)
);

--=====================================================================
-- 4. CCCMINMAXWINSOR — audit winsorizare per SKU si rulare
--=====================================================================

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CCCMINMAXWINSOR' AND xtype='U')
CREATE TABLE CCCMINMAXWINSOR (
    RUNID INT NOT NULL,
    COMPANY SMALLINT NOT NULL,
    MTRL INT NOT NULL,
    POSITIVE_LINE_COUNT INT NOT NULL,
    P95_QTY DECIMAL(28, 8) NULL,
    MEDIAN_QTY DECIMAL(28, 8) NULL,
    PRAG_APLICAT VARCHAR(10) NOT NULL,
    NR_LINII_PLAFONATE INT NULL,
    QTY_BRUT DECIMAL(28, 8) NULL,
    QTY_WINSORIZAT DECIMAL(28, 8) NULL,
    CONSTRAINT PK_CCCMINMAXWINSOR PRIMARY KEY CLUSTERED (RUNID, MTRL)
);

--=====================================================================
-- 5. CCCMINMAXGRP — clasificare ABC-XYZ pe MTRGROUP x filiala
--    Scris de sp_MinMaxEngine_ClassifyGroup cu @Persist = 1.
--    Granularitate diferita de CCCMINMAXDET, deci tabel separat.
--=====================================================================

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CCCMINMAXGRP' AND xtype='U')
CREATE TABLE CCCMINMAXGRP (
    RUNID INT NOT NULL,
    COMPANY SMALLINT NOT NULL,
    AZI DATE NOT NULL,
    BRANCH SMALLINT NOT NULL,
    MARIME VARCHAR(6) NULL,
    ESTE_HQ BIT NOT NULL,
    ESTE_PODEA BIT NOT NULL,
    MTRGROUP INT NOT NULL,
    MTRGROUP_CODE VARCHAR(10) NULL,
    MTRGROUP_NAME VARCHAR(50) NULL,
    NR_SKU_GRP INT NULL,
    NR_SKU_VZ INT NULL,
    VZ_4S DECIMAL(28, 8) NULL,
    VZ_13S DECIMAL(28, 8) NULL,
    VZ_26S DECIMAL(28, 8) NULL,
    VZ_52S DECIMAL(28, 8) NULL,
    VAL_52S DECIMAL(28, 8) NULL,
    SAPT_VZ INT NULL,
    SAPT_8S INT NULL,
    SAPT_FARA INT NULL,
    ULT_VANZ DATETIME NULL,
    SIGMA_WK DECIMAL(28, 8) NULL,
    LUNI_VZ INT NULL,
    MAX_LUNA_QTY DECIMAL(28, 8) NULL,
    MEAN_MTH DECIMAL(28, 8) NULL,
    SIGMA_MTH DECIMAL(28, 8) NULL,
    CV DECIMAL(28, 8) NULL,
    IS_FORCED_Z BIT NULL,
    LIFECYCLE VARCHAR(10) NULL,
    ABC VARCHAR(1) NULL,
    XYZ VARCHAR(1) NULL,
    CLASA VARCHAR(3) NULL,
    PREV_CUMULATIVE_PCT DECIMAL(28, 8) NULL,
    CUMULATIVE_PCT DECIMAL(28, 8) NULL,
    BR_TOTAL_VAL DECIMAL(28, 8) NULL,
    BR_GROUP_COUNT INT NULL,
    CONSTRAINT PK_CCCMINMAXGRP PRIMARY KEY CLUSTERED (RUNID, BRANCH, MTRGROUP)
);

--=====================================================================
-- 6. Aliniere coloane pentru instalari existente
--    Sectiunea 2 e IF NOT EXISTS, deci un tabel deja creat nu isi schimba
--    singur tipurile. Fiecare ALTER e no-op cand tipul este deja corect.
--    Aici se adauga si coloanele fazelor urmatoare (Faza 3 = calcul).
--=====================================================================

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='MTRL_NAME' AND DATA_TYPE <> 'varchar')
ALTER TABLE CCCMINMAXDET ALTER COLUMN MTRL_NAME VARCHAR(128) NULL;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='MTRGROUP_CODE' AND DATA_TYPE <> 'varchar')
ALTER TABLE CCCMINMAXDET ALTER COLUMN MTRGROUP_CODE VARCHAR(10) NULL;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='MTRGROUP_NAME' AND DATA_TYPE <> 'varchar')
ALTER TABLE CCCMINMAXDET ALTER COLUMN MTRGROUP_NAME VARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='SIGMA_WK_SUMSQ')
ALTER TABLE CCCMINMAXDET ADD SIGMA_WK_SUMSQ DECIMAL(38, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='SIGMA_MTH_SUMSQ')
ALTER TABLE CCCMINMAXDET ADD SIGMA_MTH_SUMSQ DECIMAL(38, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='COMPUTE_STATUS')
ALTER TABLE CCCMINMAXRUN ADD COMPUTE_STATUS VARCHAR(10) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='COMPUTE_STARTEDAT')
ALTER TABLE CCCMINMAXRUN ADD COMPUTE_STARTEDAT DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='COMPUTE_FINISHEDAT')
ALTER TABLE CCCMINMAXRUN ADD COMPUTE_FINISHEDAT DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='COMPUTE_DURATA_SEC')
ALTER TABLE CCCMINMAXRUN ADD COMPUTE_DURATA_SEC INT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='COMPUTE_PARAMSJSON')
ALTER TABLE CCCMINMAXRUN ADD COMPUTE_PARAMSJSON NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='COMPUTE_ERRORMSG')
ALTER TABLE CCCMINMAXRUN ADD COMPUTE_ERRORMSG NVARCHAR(500) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='STOC_QTY')
ALTER TABLE CCCMINMAXDET ADD STOC_QTY DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='ORD_FURN')
ALTER TABLE CCCMINMAXDET ADD ORD_FURN DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='N_PACK')
ALTER TABLE CCCMINMAXDET ADD N_PACK DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='ERP_MIN')
ALTER TABLE CCCMINMAXDET ADD ERP_MIN DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='ERP_MAX')
ALTER TABLE CCCMINMAXDET ADD ERP_MAX DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='ERP_MIN_AUTO')
ALTER TABLE CCCMINMAXDET ADD ERP_MIN_AUTO DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='ERP_MAX_AUTO')
ALTER TABLE CCCMINMAXDET ADD ERP_MAX_AUTO DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='LAST_RECEIPT')
ALTER TABLE CCCMINMAXDET ADD LAST_RECEIPT DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='ARE_POZITIE_ERP')
ALTER TABLE CCCMINMAXDET ADD ARE_POZITIE_ERP BIT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='FLAG_LICHIDARE')
ALTER TABLE CCCMINMAXDET ADD FLAG_LICHIDARE BIT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='FLAG_BLOCAT')
ALTER TABLE CCCMINMAXDET ADD FLAG_BLOCAT BIT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='FLAG_EXCLUS')
ALTER TABLE CCCMINMAXDET ADD FLAG_EXCLUS BIT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='SAFETY')
ALTER TABLE CCCMINMAXDET ADD SAFETY DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='LT_STOCK')
ALTER TABLE CCCMINMAXDET ADD LT_STOCK DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='SLTS')
ALTER TABLE CCCMINMAXDET ADD SLTS DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='BUF')
ALTER TABLE CCCMINMAXDET ADD BUF DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='CYCLE')
ALTER TABLE CCCMINMAXDET ADD CYCLE DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='MAX_RAW')
ALTER TABLE CCCMINMAXDET ADD MAX_RAW DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='MAX_INF')
ALTER TABLE CCCMINMAXDET ADD MAX_INF DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='CAP6')
ALTER TABLE CCCMINMAXDET ADD CAP6 DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='VZ26_CAP')
ALTER TABLE CCCMINMAXDET ADD VZ26_CAP DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='SUM_BR_MAX')
ALTER TABLE CCCMINMAXDET ADD SUM_BR_MAX DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='ENG_MIN')
ALTER TABLE CCCMINMAXDET ADD ENG_MIN DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='ENG_MAX')
ALTER TABLE CCCMINMAXDET ADD ENG_MAX DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='BUY_RAW')
ALTER TABLE CCCMINMAXDET ADD BUY_RAW DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='BUY_QTY')
ALTER TABLE CCCMINMAXDET ADD BUY_QTY DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='HQ_CAP_APLICAT')
ALTER TABLE CCCMINMAXDET ADD HQ_CAP_APLICAT BIT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='PODEA_APLICATA')
ALTER TABLE CCCMINMAXDET ADD PODEA_APLICATA BIT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='ACOP_CUR')
ALTER TABLE CCCMINMAXDET ADD ACOP_CUR DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='FLAG_RATIO')
ALTER TABLE CCCMINMAXDET ADD FLAG_RATIO DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='FLAG_TXT')
ALTER TABLE CCCMINMAXDET ADD FLAG_TXT VARCHAR(20) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='TREND_PCT')
ALTER TABLE CCCMINMAXDET ADD TREND_PCT DECIMAL(28, 8) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='STATUS_TREND')
ALTER TABLE CCCMINMAXDET ADD STATUS_TREND VARCHAR(20) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='DISC_FLAG')
ALTER TABLE CCCMINMAXDET ADD DISC_FLAG BIT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='WARN_VZ26_ZERO')
ALTER TABLE CCCMINMAXDET ADD WARN_VZ26_ZERO BIT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='WARN_STOC_NEG')
ALTER TABLE CCCMINMAXDET ADD WARN_STOC_NEG BIT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXDET' AND COLUMN_NAME='WARN_STOC_MORT')
ALTER TABLE CCCMINMAXDET ADD WARN_STOC_MORT BIT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='GROUP_STATUS')
ALTER TABLE CCCMINMAXRUN ADD GROUP_STATUS VARCHAR(10) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='GROUP_STARTEDAT')
ALTER TABLE CCCMINMAXRUN ADD GROUP_STARTEDAT DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='GROUP_FINISHEDAT')
ALTER TABLE CCCMINMAXRUN ADD GROUP_FINISHEDAT DATETIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='GROUP_DURATA_SEC')
ALTER TABLE CCCMINMAXRUN ADD GROUP_DURATA_SEC INT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='GROUP_NR_RANDURI')
ALTER TABLE CCCMINMAXRUN ADD GROUP_NR_RANDURI INT NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='GROUP_PARAMSJSON')
ALTER TABLE CCCMINMAXRUN ADD GROUP_PARAMSJSON NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='GROUP_ERRORMSG')
ALTER TABLE CCCMINMAXRUN ADD GROUP_ERRORMSG NVARCHAR(500) NULL;

-- Sesiunea de calcul. NULL pe rularile vechi inseamna "legacy, inghetata,
-- nu este referinta" — exact semantica dorita, deci nu se face backfill.
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='SESSION_STATUS')
ALTER TABLE CCCMINMAXRUN ADD SESSION_STATUS VARCHAR(10) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='SCOPE')
ALTER TABLE CCCMINMAXRUN ADD SCOPE VARCHAR(10) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME='CCCMINMAXRUN' AND COLUMN_NAME='ESTE_CURENT')
ALTER TABLE CCCMINMAXRUN ADD ESTE_CURENT BIT NULL;
